server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      embled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        '[hibernate.format_sql]': true

  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': DEBUG
